services:
  # API Gateway
  api-gateway:
    build:
      context: ./backend/ApiGateway/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - produto-service
      - usuario-service
    networks:
      - microservices-network

  # Produto Service (inclui funcionalidade de estoque)
  produto-service:
    build:
      context: ./backend/ProdutoService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProdutosDB;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=true;
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - microservices-network

  # Usuario Service
  usuario-service:
    build:
      context: ./backend/UsuarioService/UsuarioService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UsuariosDB;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=true;
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - microservices-network

  # Frontend Angular
  frontend:
    build:
      context: ./frontend/estoque-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - microservices-network

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P StrongPassword123! -C -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - microservices-network

  # Redis (para cache entre microsserviços)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  sqlserver_data:
