@ProdutoService_HostAddress = http://localhost:5001
@ApiGateway_HostAddress = http://localhost:5000

# Testes diretos no ProdutoService
GET {{ProdutoService_HostAddress}}/api/produtos
Accept: application/json

###

GET {{ProdutoService_HostAddress}}/api/produtos/1
Accept: application/json

###

GET {{ProdutoService_HostAddress}}/api/produtos/pesquisar?termo=teste
Accept: application/json

###

GET {{ProdutoService_HostAddress}}/api/estoque
Accept: application/json

###

GET {{ProdutoService_HostAddress}}/api/estoque/pesquisar?termo=teste
Accept: application/json

###

PUT {{ProdutoService_HostAddress}}/api/estoque/1/quantidade
Content-Type: application/json

50

###

# Testes via API Gateway
GET {{ApiGateway_HostAddress}}/api/produtos
Accept: application/json

###

GET {{ApiGateway_HostAddress}}/api/estoque
Accept: application/json

###

GET {{ApiGateway_HostAddress}}/api/estoque/pesquisar?termo=teste
Accept: application/json

###
